name: hnyuan

on:
  schedule:
    - cron: '0 10,06,02 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet  pypinyin  bs4

      - name: Install Chrome WebDriver
        run: |
         LATEST_CHROMEDRIVER_VERSION=124.0.6367.78
         curl -sS -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver-linux64.zip"
         sudo unzip chromedriver_linux64.zip -d /usr/local/bin
         sudo rm chromedriver_linux64.zip

         if [ ! -f "/usr/local/bin/chromedriver" ]; then
         echo "chromedriver not found."
         exit 1
         fi

         sudo rm /usr/local/bin/chromedriver || true

         # 注意：这步可能不需要，因为 chromedriver 已经解压到了 /usr/local/bin/
         # sudo ln -sf /usr/local/bin/chromedriver /usr/local/bin/chromedriver

         sudo chmod +x /usr/local/bin/chromedriver

         /usr/local/bin/chromedriver --version
    
      - name: Run hunan
        run: python ${{ github.workspace }}/hnyuan.py
                               
      - name: 提交更改
        run: |
          git config --local user.email "mlyuanlang@126.com"
          git config --local user.name "mlvjfchen"
          git add .
          git commit *.txt -m "Add generated file"
          # git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
